/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CRM.view.MainPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainpanel',

    id: 'MainPanel',
    activeTab: 0,
    plain: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                render: {
                    fn: me.onMainPanelRender,
                    scope: me
                }
            },
            items: [
                {
                    xtype: 'panel',
                    html: 'hello',
                    title: '#',
                    tabConfig: {
                        xtype: 'tab',
                        margin: '0 1 0 200',
                        tooltip: 'Главная'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'MyButton'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    border: false,
                    layout: {
                        type: 'border'
                    },
                    title: 'База объявлений',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            store: 'BulletinStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'id',
                                    text: 'ИД'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'title',
                                    text: 'Заголовок',
                                    flex: 1
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'created',
                                    text: 'Опубликовано'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'type',
                                    text: 'Тип'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'price',
                                    text: 'Цена'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'BulletinStore'
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'buttongroup',
                                            defaults: 'scale: \'medium\'',
                                            title: 'Фильтр',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    scale: 'medium',
                                                    text: 'Тип сделки',
                                                    menu: {
                                                        xtype: 'menu',
                                                        items: [
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: 'Купля'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: 'Продажа'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    scale: 'medium',
                                                    text: 'Количество комнат',
                                                    menu: {
                                                        xtype: 'menu',
                                                        items: [
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: '1-а комнатные'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: '2-х комнатные'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: '3-х комнатные'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: '4-х комнатные'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: '5-ти комнатные'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: '> 5-ти комнатные'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    scale: 'medium',
                                                    text: 'Применить фильтр'
                                                },
                                                {
                                                    xtype: 'button',
                                                    scale: 'medium',
                                                    text: 'Сохранить фильтр'
                                                },
                                                {
                                                    xtype: 'button',
                                                    scale: 'medium',
                                                    text: 'Загрузить фильтр'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                selectionchange: {
                                    fn: me.onGridpanelSelectionChange,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'panel',
                            region: 'east',
                            split: true,
                            border: false,
                            width: 400,
                            layout: {
                                type: 'border'
                            },
                            collapsed: false,
                            collapsible: true,
                            header: false,
                            items: [
                                {
                                    xtype: 'panel',
                                    region: 'center',
                                    header: false,
                                    title: 'My Panel'
                                },
                                {
                                    xtype: 'panel',
                                    region: 'south',
                                    split: true,
                                    height: 300,
                                    html: '<div id="bsingle-map"></div>',
                                    collapsible: true,
                                    title: 'Карта',
                                    listeners: {
                                        afterrender: {
                                            fn: me.onPanelAfterRender1,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    loader: {
                        url: '/ext/bulletin/map',
                        autoLoad: true
                    },
                    width: 150,
                    title: 'Карта',
                    listeners: {
                        afterrender: {
                            fn: me.onPanelAfterRender,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onMainPanelRender: function(component, eOpts) {
        return;
        var tabs_model = Ext.create('CRM.store.MainPanelStore');

        tabs_model.addListener('load', function(store, records){
            store.each(function(rec){

                //rec.xtype = 'panel';

                rec.data.items = [{xtype:'panel'}];

                component.add(rec.data);
            });
        });

    },

    onGridpanelSelectionChange: function(model, selected, eOpts) {

        console.log(selected[0].data);
    },

    onPanelAfterRender1: function(component, eOpts) {

        return;

        var mpanel = document.getElementById('panel-1056');

        var map_element = document.getElementById('bsingle-map');

        map_element.style.height = mpanel.style.height;
        map_element.style.width  = mpanel.style.width;



        // Создание экземпляра карты и его привязка к контейнеру с
        // заданным id ("map")
        var myMap = new ymaps.Map('bullet-ymap', {
            // При инициализации карты, обязательно нужно указать
            // ее центр и коэффициент масштабирования
            center: [55.76, 37.64], // Москва
            zoom: 10
        });
    },

    onPanelAfterRender: function(component, eOpts) {

        var mpanel = document.getElementById('MainPanel-body');

        var map_element = document.getElementById('bullet-ymap');

        map_element.style.height = mpanel.style.height;
        map_element.style.width  = mpanel.style.width;



        // Создание экземпляра карты и его привязка к контейнеру с
        // заданным id ("map")
        var myMap = new ymaps.Map('bullet-ymap', {
            // При инициализации карты, обязательно нужно указать
            // ее центр и коэффициент масштабирования
            center: [55.76, 37.64], // Москва
            zoom: 14
        });

    }

});